---
deployment:
  tasks:
    - export DEPLOYPATH=/home/$USER/Souley-Guirou.danayaplus.com
    - if [ ! -d "$DEPLOYPATH" ]; then export DEPLOYPATH=/home/$USER/public_html; fi
    - /bin/cp -R * $DEPLOYPATH
    - /bin/chmod 755 $DEPLOYPATH/pharmacie-gestion 2>/dev/null || true
